bookmark/urls.py
from django.views.generic import ListView, DeleteView
from bookmark.models import Bookmark
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

app_name = 'bookmark'
urlpatterns = [

    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    # ex) /bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name='add',),

    # ex) /bookmark/change/
    path('change/', views.BookmarkChangeLV.as_view(), name='change',),

    # ex) /bookmark/99/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update",),

    # ex) /bookmark/99/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete",),

]

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

#--- ListView
class BookmarkLV(ListView):
    model = Bookmark

#--- DetailView
class BookmarkDV(DetailView):
    model = Bookmark

#--- 추가
class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}bookmark_change_list.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Post</h1>
            <span class="subheading">Post List</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Bookmark Change - {{user}}</h1>
        <br>

        <table class="table table-bordered table-condensed table-striped">

            <thead>
                <tr class="table-primary">
                    <th>Title</th>
                    <th>Url</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>

            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}bookmark_confirm_delete.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Post</h1>
            <span class="subheading">Post List</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Bookmark Delete</h1>
        <br>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
        </form>

    </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Bookmark Detail {% endblock %}

{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1> Bookmark </h1>
            <span class="subheading">Bookmark Detail</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div id="content">

        <h1>{{ object.title }}</h1>

        <ul>
            <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
            <a class="btn btn-success" href="{% url 'bookmark:change' %}" role="button">수정</a>
            <a class="btn btn-danger" href="{% url 'bookmark:delete' object.id %}" role="button">삭제</a>
        </div>
{% endblock %}


{% block extra-script %}{% endblock %}



<!--
<!DOCTYPE html>
<html>
<head>
<title>Django Bookmark Detail</title>
</head>

<body>

<div id="content">

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

</div>

</body>
</html>
-->

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}bookmark_form.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Post</h1>
            <span class="subheading">Post List</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Bookmark Create/Update - {{user}}</h1>
        <p class="font-italic">This is a creation or update form for your bookmark.</p>

        {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
        {% endif %}

        <form action="." method="post" class="card pt-3">{% csrf_token %}

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.url|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group">
                <div class="offset-sm-2 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info"/>
                </div>
            </div>

        </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Bookmark {% endblock %}


{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1> Bookmark </h1>
            <span class="subheading">Bookmark List</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div id="content">

        <h1>Bookmark List</h1>

        <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
        </ul>

        <a class="btn btn-primary" href="{% url 'bookmark:add' %}" role="button">새 북마크 등록</a>
      </div>
{% endblock %}


{% block extra-script %}{% endblock %}