photo/urls.py
from django.urls import path
from photo import views


app_name = 'photo'
urlpatterns = [

    # ex) /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # ex) /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    # ex) /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # ex) /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

# --- /photo/album/ (add, change, update, delete)
    # ex) /photo/album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # ex) /photo/album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # ex) /photo/album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # ex) /photo/album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

# --- /photo/photo/ (add, change, update, delete)
    # ex) /photo/photo/add/
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    # ex) /photo/photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # ex) /photo/photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),

    # ex) /photo/photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

]




# from django.urls import path
# from django.views.generic import ListView, DetailView

# from photo.models import Album,Photo

# app_name = 'photo'
# urlpatterns = [

    # ex) /photo/
    # path('', ListView.as_view(model=Album), name='index'),

    # ex) /photo/album/, same as /photo/
    # path('', ListView.as_view(model=Album), name='album_list'),

    # ex) /photo/album/99/
    # path('album/<int:pk>/', DetailView.as_view(model=Album), name='album_detail'),

    # ex) /photo/album/99/
    # path('photo/<int:pk>/', DetailView.as_view(model=Photo), name='photo_detail'),

# ]

photo/forms.py
from django.forms import inlineformset_factory
from photo.models import Album, Photo

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

photo/templates/photo/album_change_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}album_change_list.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Album</h1>
            <span class="subheading">Change</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Album Change - {{user}}</h1>

        <table class="table table-striped table-bordered table-condensed">

            <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>

            <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}album_confirm_delete.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Album</h1>
            <span class="subheading">Delete</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
        <br>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
        </form>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Album Detail {% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Album</h1>
            <span class="subheading">Detail</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block extra-style %}
<style>
thumbnail {
    border: 5px solid #ccc;
}
</style>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="mt-5">
            <span class="h2">{{ object.name }}&emsp;</span>
            <span class="h5 font-italic">{{ object.description }}</span>
        </div>

        <hr style="margin: 0 0 20px 0;">

        <div class="row">

            {% for photo in object.photo_set.all %}
            <div class="col-md-3 mb-5">
                <div class="thumbnail">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
                <ul>
                    <li class="font-italic">{{ photo.title }}</li>
                    <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
                </ul>
            </div>
            {% endfor %}


        </div>

        <a class="btn btn-primary" href="{% url 'photo:photo_add' %}" role="button">사진 추가</a>
        <a class="btn btn-success" href="{% url 'photo:album_change' %}" role="button">앨범 수정</a>
        <a class="btn btn-danger" href="{% url 'photo:album_delete' object.id %}" role="button">앨범 삭제</a>

{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}album_form.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Album</h1>
            <span class="subheading">Form</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Album-Photo Create/Update - {{user}}</h1>
        <p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>

        {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
            {{ form.errors }}
        </div>
        {% endif %}

        {% if formset.errors %}
        <div class="alert alert-warning">
            <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
            {% for formerrors in formset.errors %}
                {{ formerrors }}
            {% endfor %}
        </div>
        {% endif %}

        {% if form.is_multipart or formset.is_multipart %}
        <form enctype="multipart/form-data" action="" method="post">
        {% else %}
        <form action="." method="post">
        {% endif %}
        {% csrf_token %}

            <h4>create or update album contents</h4>

            <fieldset class="card pt-3">

                <div class="form-group row">
                    {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.description|add_class:"form-control" }}
                    </div>
                </div>

            </fieldset>
            <br>

            <h4>create or update photo contents</h4>

            <fieldset class="card pt-3">

                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form.id }}
                    {# form.album #}
                <div class="form-group row">
                    {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.image|add_class:"form-control-file" }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.title|add_class:"form-control" }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-8">
                        {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                    </div>
                </div>

                <hr>
                {% endfor %}

            </fieldset>

            <div class="form-group card py-1">
                <div class="offset-sm-3 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info"/>
                </div>
            </div>

        </form>
{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Album List {% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Album</h1>
            <span class="subheading">List</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block extra-style %}
<style>
thumbnail {
    border: 3px solid #ccc;
}
</style>
{% endblock %}



{% block content %} 
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in object_list %}

        <div class="mt-5">
            <a class="h2" href="{% url 'photo:album_detail' item.id %}">
            {{ item.name }}</a>&emsp;
            <span class="font-italic h5">{{ item.description }}</span>
        </div>

        <hr style="margin: 0 0 20px 0;">

        <div class="row">
            {% for photo in item.photo_set.all|slice:":5" %}
            <div class="ml-5">
                <div class="thumbnail">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <a class="btn btn-primary" href="{% url 'photo:album_add' %}" role="button">앨범 추가</a>

        {% endfor %}
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}photo_change_list.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Photo</h1>
            <span class="subheading">Change</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Photo Change - {{user}}</h1>

        <table class="table table-striped table-bordered table-condensed">

            <thead>
            <tr class="table-info">
                <th>Album</th>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>

            <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.album }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}photo_confirm_delete.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Photo</h1>
            <span class="subheading">Delete</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Photo Delete</h1>
        <br>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
        </form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Photo Detail {% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Photo</h1>
            <span class="subheading">Detail</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h2 class="mt-5">{{ object.title }}</h2>

        <div class="row">
            <div class="col-md-9">
                <a href="{{ object.image.url }}">
                    <img src="{{ object.image.url }}" style="width: 100%;">
                </a>
            </div>

            <ul class="col-md-3 mt-3">
                <li class="h5">Photo Description</li>
                    {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                    {% else %}<p>(blank)</p>{% endif %}
                <li class="h5">Date Uploaded</li>
                    <p class="font-italic">{{ object.upload_dt }}</p>
                <li class="h5">Album Name</li>
                    <p class="font-italic">
                        <a href="{% url 'photo:album_detail' object.album.id %}"> {{ object.album.name }}</a>
                    </p>
            </ul>

            <a class="btn btn-success" href="{% url 'photo:photo_change' %}" role="button">사진 수정</a>
            <a class="btn btn-danger" href="{% url 'photo:photo_delete' object.id %}" role="button">사진 삭제</a>

        </div>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}photo_form.html{% endblock %}



{% block header %}
 <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Photo</h1>
            <span class="subheading">Form</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>Photo Create/Update - {{user}}</h1>
        <p class="font-italic">This is a creation or update form for your photo.</p>

        {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
        {% endif %}

        {% if form.is_multipart %}
        <form enctype="multipart/form-data" action="" method="post" class="card pt-3">
        {% else %}
        <form action="." method="post" class="card pt-3">
        {% endif %}
        {% csrf_token %}

            <div class="form-group row">
                {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-2">
                    {{ form.album|add_class:"form-control" }}
                </div>
                <div class="col-sm-2 my-auto">
                    <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">
                    Add Album</a>
                </div>
            </div>

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <div class="form-group">
                <div class="offset-sm-2 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info"/>
                </div>
            </div>

        </form>
{% endblock %}